name: UnitTest

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  GO111MODULE: on

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.18, 1.21, 1.24]
        db: [SQLite3]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Go ${{ matrix.go }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Setup Go Tools
        run: |
          go mod download
          export PATH="${GOPATH}/bin:${GOROOT}/bin:${PATH}"

      - name: Test
        run: go test -test.short ./... -race -coverprofile=coverage.txt -covermode=atomic

      - name: Codecov Report
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
